In [2]:
import numpy

In [2]:
import numpy as np

In [5]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [7]:
y = np.array([[1,2,3], ['a', 'b', 'c']])
print(y)


[['1' '2' '3']
 ['a' 'b' 'c']]


In [8]:
tablica_zespolona = np.array([[1,0], [0,1]], dtype=complex)
print(tablica_zespolona)

[[ 1.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j]]


In [13]:
print(np.arange(0,100, 17))
print(np.arange(0., -100, -3.3))

[ 0 17 34 51 68 85]
[  0.   -3.3  -6.6  -9.9 -13.2 -16.5 -19.8 -23.1 -26.4 -29.7 -33.  -36.3
 -39.6 -42.9 -46.2 -49.5 -52.8 -56.1 -59.4 -62.7 -66.  -69.3 -72.6 -75.9
 -79.2 -82.5 -85.8 -89.1 -92.4 -95.7 -99. ]


In [23]:
print(np.linspace(0,6,7))

[ 0.  1.  2.  3.  4.  5.  6.]


In [30]:
print(np.zeros((3,9)))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [31]:
print(np.linspace(0,14, 15).reshape((3,5)))

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]]


In [46]:
m = np.arange(0,20).reshape((4,5))
print(m[:,[1,3]])

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [52]:
A = np.arange(20).reshape(5,4)
print(A, '\n')

B = A[0:3, 0:2]
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[0 1]
 [4 5]
 [8 9]]


In [59]:

A = np.arange(8)
A.resize(2, 4)
# print(A.resize(2, 4), '\n')
print(A)

[[0 1 2 3]
 [4 5 6 7]]


In [60]:
A.shape, A.size

((2, 4), 8)

In [63]:
print(A.T.T)

[[0 1 2 3]
 [4 5 6 7]]


In [65]:
np.transpose()

array([], shape=(0, 2), dtype=float64)

In [68]:
A = np.arange(8).reshape(2,4)
print(A, '\n')
print(np.ravel(A), '\n')
print(A.reshape(-1,4))

[[0 1 2 3]
 [4 5 6 7]] 

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]]
